letsencrypt_email: ned@baldessin.fr

php_extra_packages:
  - php-intl

server_locales:
  - en_US.UTF-8
  - fr_FR.UTF-8

default_locale: "fr_FR.UTF-8"
postgresql_locale: "fr_FR.UTF-8"

postgresql_databases:
  - name: gobelins
    encoding: UTF8
    lc_collate: "fr_FR.UTF-8"
    lc_ctype: "fr_FR.UTF-8"

postgresql_users:
  - name: gobelins
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64346431373666343364613364656433393464663337363638303831333161346464353435393132
      3862636238383565396539363934323837653336633539390a633130616334323234306133663933
      61386539623465303636396634303131626236303538653164376437306435323363303134353336
      3964393532653861360a326464656333663339393434343064316263393838323331303739326534
      34646230363261383466333636623632393165316565376366653261613734306562
